# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c46316b3420aab3e17bed5d1679fde8567dad40a78b0574745e28b66c2d3a3d9fc49f1ebbeb4f9a3d7a3f7bb98f6ff0b58801d61d1ca4fbb4b917007425d760a

test:
  secret_key_base: ac30f093ec33a0ba92672a44b3676ab5e461625a21d5726279aff9c3504529c5fc6f2a15600bb25a6ce72701562e0a788fd3c6fd8cc4b50105005d380af88e37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
